FROM python:3.12-slim

WORKDIR /player
COPY players/ordinary/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY players/ordinary/*.py .
COPY players/ordinary/system_prompt.txt .

CMD ["python", "player.py"]
